# apps bindings: SUPER SHIFT
bindd = SUPER, RETURN, Terminal, exec, uwsm-app -- xdg-terminal-exec --dir="$(omarchy-cmd-terminal-cwd)"
bindd = SUPER SHIFT, B, Browser, exec, omarchy-launch-browser
bindd = SUPER SHIFT, F, File manager, exec, uwsm-app -- nautilus --new-window
bindd = SUPER SHIFT, M, Youtube-Music, exec, omarchy-launch-or-focus pear-desktop
bindd = SUPER SHIFT, O, Obsidian, exec, omarchy-launch-or-focus ^obsidian$ "uwsm-app -- obsidian"
bindd = SUPER SHIFT, D, Discord, exec, omarchy-launch-or-focus discord-canary

# controll tilling: SUPER CTRL, SUPER CTRL SHIFT
unbind = SUPER, F
unbind = SUPER CTRL, F
unbind = SUPER, W
unbind = SUPER SHIFT, W
unbind = SUPER CTRL, X
unbind = SUPER CTRL SHIFT, X
unbind = SUPER ALT, DELETE
unbind = SUPER, T
unbind = SUPER, P
unbind = SUPER CTRL, P

bind = SUPER CTRL, F, fullscreen,
bind = SUPER CTRL, X, killactive,
bind = SUPER CTRL SHIFT, X, exec, omarchy-hyprland-window-close-all
bind = SUPER CTRL, P, togglefloating

# move focus: SUPER
unbind = SUPER, LEFT
unbind = SUPER, RIGHT
unbind = SUPER, H
unbind = SUPER, L
unbind = SUPER, DOWN
unbind = SUPER, UP

bind = SUPER, H, movefocus, l
bind = SUPER, L, movefocus, r

# switch workspaces: SUPER
unbind = SUPER, K
unbind = SUPER, J
unbind = SUPER, G

bindr = SUPER, Super_L, scrolloverview:overview, toggle
submap = scrolloverview
  bind = , h, scrolloverview:navigate, left
  bind = , l, scrolloverview:navigate, right
  bind = , k, scrolloverview:navigate, up
  bind = , j, scrolloverview:navigate, down
  bind = , return, scrolloverview:overview, disable
  bind = , return, submap, reset
  bind = , x, scrolloverview:window, close

  bind = SUPER, RETURN, exec, uwsm-app -- xdg-terminal-exec --dir="$(omarchy-cmd-terminal-cwd)"
  bind = SUPER SHIFT, B, exec, omarchy-launch-browser
  bind = SUPER SHIFT, F,exec, uwsm-app -- nautilus --new-window
  bind = SUPER SHIFT, M, exec, omarchy-launch-or-focus pear-desktop
  bind = SUPER SHIFT, O, exec, omarchy-launch-or-focus ^obsidian$ "uwsm-app -- obsidian"
  bind = SUPER SHIFT, D, exec, omarchy-launch-or-focus discord-canary
submap = reset

# switch active window with the one next to it: SUPER SHIFT
unbind = SUPER SHIFT, H 
unbind = SUPER SHIFT, L

bind = SUPER SHIFT, H, swapwindow, l
bind = SUPER SHIFT, L, swapwindow, r

