bindd = SUPER, RETURN, Terminal, exec, uwsm-app -- xdg-terminal-exec --dir="$(omarchy-cmd-terminal-cwd)"
bindd = SUPER, B, Browser, exec, omarchy-launch-browser
bindd = SUPER SHIFT, F, File manager, exec, uwsm-app -- nautilus --new-window
bindd = SUPER SHIFT, M, Music, exec, omarchy-launch-or-focus pear-desktop
bindd = SUPER SHIFT, O, Obsidian, exec, omarchy-launch-or-focus ^obsidian$ "uwsm-app -- obsidian"
bindd = SUPER SHIFT, D, Discord, exec, omarchy-launch-or-focus discord-canary

# controll tilling
unbind = SUPER, F
bind = SUPER, F, fullscreen,
unbind = SUPER, W
bind = SUPER, X, killactive,
unbind = SUPER ALT, DELETE
bind = SUPER SHIFT, X, exec, omarchy-hyprland-window-close-all
unbind = SUPER, T
unbind = SUPER, P
bind = SUPER, P, togglefloating

# move focus
unbind = SUPER, LEFT
unbind = SUPER, H
bind = SUPER, H, movefocus, l
unbind = SUPER, RIGHT
unbind = SUPER, L
bind = SUPER, L, movefocus, r
unbind = SUPER, DOWN
unbind = SUPER, UP

# switch workspaces
unbind = SUPER, K
bind = SUPER, K, workspace, m+1
unbind = SUPER, J
bind = SUPER, J, workspace, m-1

# move window to a workspace
unbind = SUPER SHIFT, K
bind = SUPER SHIFT, K, movetoworkspace, m+1 
unbind = SUPER SHIFT, J
bind = SUPER SHIFT, J, movetoworkspace, m-1

# switch active window with the one next to it
unbind = SUPER SHIFT, H 
bind = SUPER SHIFT, H, swapwindow, l
unbind = SUPER SHIFT, L
bind = SUPER SHIFT, L, swapwindow, r

# Add extra bindings
# bind = SUPER SHIFT, R, exec, alacritty -e ssh your-server

# Overwrite existing bindings, like putting Omarchy Menu on Super + Space
# unbind = SUPER, SPACE
# bindd = SUPER, SPACE, Omarchy menu, exec, omarchy-menu
